<template>
  <section class="py-20 bg-blue-pale">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center">
        <h2 class="text-3xl font-extrabold text-white sm:text-4xl">
          Hailuo AI Video Showcase
        </h2>
        <p class="mt-4 text-xl text-gray-300">
          This is an amazing video demo generated by Hailuo AI technology, showcasing advanced AI video generation capabilities. The video content includes rich visual effects and smooth animations, demonstrating the enormous potential of AI in creative content creation.
        </p>
      </div>
      
      <div class="mt-16 max-w-10xl mx-auto">
        <div class="bg-blue-pale/80 rounded-lg overflow-hidden shadow-xl">
          <div class="relative flex items-center justify-center bg-black">
            <!-- Loading state -->
            <div v-if="isLoading" class="absolute inset-0 flex justify-center items-center bg-black/50 z-10">
              <div class="animate-spin rounded-full h-12 w-12 border-4 border-[#7C3AED] border-t-transparent"></div>
            </div>
            
            <!-- Video element -->
            <video
              ref="videoRef"
              :src="videoSrc"
              :poster="posterSrc"
              class="w-full h-auto min-h-[400px] max-h-[600px] object-cover"
              :preload="isIntersecting ? 'auto' : 'none'"
              @ended="onVideoEnded"
              @click="togglePlay"
              @loadstart="onLoadStart"
              @canplay="onCanPlay"
              @error="onVideoError"
              @waiting="onVideoWaiting"
              @playing="onVideoPlaying"
              @pause="onVideoPause"
              @timeupdate="onTimeUpdate"
              playsinline
              webkit-playsinline
              x5-playsinline
              x5-video-player-type="h5"
              x5-video-player-fullscreen="false"
              :alt="videoAlt"
              :title="videoTitle"
              muted
              autoplay
            ></video>
            
            <!-- Video info overlay -->
            <!-- <div v-if="!isPlaying" class="absolute bottom-4 left-4 right-4 bg-black bg-opacity-70 text-white p-4 rounded">
              <h3 class="text-lg font-semibold mb-2">{{ videoTitle }}</h3>
              <p class="text-sm text-gray-300">{{ videoDescription }}</p>
            </div> -->
          </div>
          
          <!-- Video information -->
          <!-- <div class="p-6 text-gray-200">
            <h3 class="text-xl font-semibold mb-4">{{ videoTitle }}</h3>
            <p class="text-base leading-relaxed">{{ videoDescription }}</p>
          </div> -->
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue';

// Video configuration
const videoSrc = 'https://resource.hailuo2.com/hailuo/video/hailuo2-video.mp4'
const posterSrc = '/img/hailuo2 video.webp'
const videoTitle = 'Hailuo AI Video Generation Demo'
const videoDescription = 'This is an amazing video demo generated by Hailuo AI technology, showcasing advanced AI video generation capabilities. The video content includes rich visual effects and smooth animations, demonstrating the enormous potential of AI in creative content creation.'
const videoAlt = 'Hailuo AI video generation technology demo, showcasing AI video creation capabilities'
const playButtonAriaLabel = 'Play Hailuo AI video demo'

// Reactive state
const videoRef = ref<HTMLVideoElement | null>(null)
const isPlaying = ref(false)
const isLoading = ref(false)
const isIntersecting = ref(false)
const shouldLoop = ref(true)

// Video playback control
async function togglePlay() {
  try {
    const videoElement = videoRef.value
    if (!videoElement) return

    if (isPlaying.value) {
      videoElement.pause()
      isPlaying.value = false
      isLoading.value = false
    } else {
      isLoading.value = true
      isPlaying.value = true
      
      // Ensure video is ready before playing
      if (videoElement.readyState < 2) {
        await new Promise((resolve) => {
          videoElement.addEventListener('canplay', resolve, { once: true })
          videoElement.load()
        })
      }
      
      const playPromise = videoElement.play()
      if (playPromise !== undefined) {
        playPromise.catch((error) => {
          console.error('Video playback error:', error)
          isLoading.value = false
          isPlaying.value = false
        })
      }
    }
  } catch (err) {
    console.error('Video control error:', err)
    isLoading.value = false
    isPlaying.value = false
  }
}

// Video event handlers
function onLoadStart() {
  if (isPlaying.value) {
    isLoading.value = true
  }
}

function onCanPlay() {
  if (isPlaying.value) {
    isLoading.value = false
  }
}

function onVideoWaiting() {
  if (isPlaying.value) {
    isLoading.value = true
  }
}

function onVideoPlaying() {
  if (isPlaying.value) {
    isLoading.value = false
  }
}

function onVideoPause() {
  if (isPlaying.value) {
    isLoading.value = false
  }
}

function onTimeUpdate() {
  // Check if video is near the end (within 0.1 seconds)
  const videoElement = videoRef.value
  if (videoElement && shouldLoop.value) {
    const timeRemaining = videoElement.duration - videoElement.currentTime
    if (timeRemaining <= 0.1 && videoElement.duration > 0) {
      // Video is about to end, prepare for restart
      nextTick(() => {
        if (isPlaying.value && shouldLoop.value) {
          videoElement.currentTime = 0
          videoElement.play().catch((error) => {
            console.error('Video restart error:', error)
          })
        }
      })
    }
  }
}

function onVideoEnded() {
  // Restart video if looping is enabled
  if (shouldLoop.value && isPlaying.value) {
    const videoElement = videoRef.value
    if (videoElement) {
      videoElement.currentTime = 0
      videoElement.play().catch((error) => {
        console.error('Video restart error:', error)
        isPlaying.value = false
      })
    }
  } else {
    isPlaying.value = false
  }
  isLoading.value = false
}

function onVideoError() {
  isLoading.value = false
  isPlaying.value = false
  console.error('Video loading error')
}

// Lazy loading - using Intersection Observer
onMounted(() => {
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          isIntersecting.value = true
          observer.unobserve(entry.target)
          // 当视频进入视口时自动播放
          if (videoRef.value) {
            isPlaying.value = true
            videoRef.value.play().catch((error) => {
              console.error('Auto-play error:', error)
              isPlaying.value = false
            })
          }
        }
      })
    },
    {
      rootMargin: '50px'
    }
  )

  if (videoRef.value) {
    observer.observe(videoRef.value)
  }

  // Cleanup function
  onUnmounted(() => {
    if (videoRef.value) {
      observer.unobserve(videoRef.value)
    }
    
    // Pause video and cleanup resources
    if (videoRef.value) {
      videoRef.value.pause()
      videoRef.value.src = ''
      videoRef.value.load()
    }
    
    isPlaying.value = false
    isLoading.value = false
  })
})
</script>

<style scoped>
/* Custom video styles */
video {
  transition: all 0.3s ease;
}

video:hover {
  transform: scale(1.02);
}

/* Play button animation */
button:hover .w-20 {
  transform: scale(1.1);
  transition: transform 0.2s ease;
}
</style> 